### ISSUE TITLE
python3 support

### ISSUE THREAD

**Issue by sgutermann** [RPi-Distro/rpi-source#11]
First of all thank you for sharing.

Considering the latest raspi images (minimal) only have python 3.9 pre-installed, you think there might be a chance of updating your script to python3 ??

Yes I do think you have better things to do, however on the off chance that you do have 20 Minutes in your life for which you have no other use, do please consider.

**Comment by dmeziere** [comment]
I think it could be related : When following the readme i got :

‘/usr/local/bin/rpi-source’ saved [14223/14223]

/usr/bin/env: ‘python2’: No such file or directory
