### ISSUE TITLE
um freeze at Module.symvers

### ISSUE THREAD

**Issue by boyphongsakorn** [RPi-Distro/rpi-source#12]
i run rpi-source
and freeze Module.symvers
how to i fix that?

**Comment by pelwell** [comment]
Somebody here may understand exactly what you are referring to, but I don't. Can you give a bit more detail? What do you mean by "freeze Module.symvers"?

**Comment by boyphongsakorn** [comment]
> Somebody here may understand exactly what you are referring to, but I don't. Can you give a bit more detail? What do you mean by "freeze Module.symvers"?

oh ok

i run rpi-source
and stuck at step Module.symvers

[![Screenshot-2566-01-18-at-07.38.30.png](https://imgul.teamquadb.in.th/images/2023/01/18/Screenshot-2566-01-18-at-07.38.30.png)](https://imgul.teamquadb.in.th/image/jry)

leaving 8 hours and still stuck

**Comment by pelwell** [comment]
Thanks. Testing on a 3B+ it's working for me - it's got as far as making module prepare. If you can open another shell - in a new window in the GUI, in another terminal with Ctrl-Alt-F2, or over ssh - try the following:
1. Run `df` to see if you have run out of disk space.
2. Run `top` to see what is currently active and what the load average is.

**Comment by pelwell** [comment]
And now the module_prepare has completed without error.

**Comment by boyphongsakorn** [comment]
um i run `sudo rpi-source` and it work fine 😂
