### ISSUE TITLE
Resolution : ImportError: No module named request

### ISSUE THREAD

**Issue by nghiank97** [RPi-Distro/rpi-source#26]
When command :  sudo chmod +x /usr/local/bin/rpi-source && /usr/local/bin/rpi-source -q --tag-update , the error occur

`
Traceback (most recent call last):
  File "/usr/local/bin/rpi-source", line 14, in <module>
    import urllib.request, urllib.parse, urllib.error
ImportError: No module named request
`

Resolution 
1. move to /usr/local/bin/rpi-source
2. open file : sudo vim /usr/local/bin/rpi-source
3. change #!/usr/bin/env python to #!/usr/bin/env python3

**Comment by Manoo089** [comment]
I become this Error: No module named 'urllib2'.

I tried this solution below. Dont work. What can I try?

**Comment by ardrabczyk** [comment]
Does:

    pi@raspberrypi:~ $ python3 $(command -v rpi-source) --help

work?

**Comment by tc0nn** [comment]
> When command : sudo chmod +x /usr/local/bin/rpi-source && /usr/local/bin/rpi-source -q --tag-update , the error occur
> 
> `Traceback (most recent call last): File "/usr/local/bin/rpi-source", line 14, in <module> import urllib.request, urllib.parse, urllib.error ImportError: No module named request`
> 
> Resolution
> 
> 1. move to /usr/local/bin/rpi-source
> 2. open file : sudo vim /usr/local/bin/rpi-source
> 3. change #!/usr/bin/env python to #!/usr/bin/env python3

While this is a fix, can we fix this in code?

**Comment by defanator** [comment]
PR fixing this issue - https://github.com/RPi-Distro/rpi-source/pull/35.
