### ISSUE TITLE
Help for processor missing

### ISSUE THREAD

**Issue by askpatrickw** [RPi-Distro/rpi-source#32]
Repo steps

```shell
$ rpi-source

ERROR:
Unexpected processor 4 (use --processor argument)

Help: https://github.com/RPi-Distro/rpi-source/blob/master/README.md
```

When you go to the README, the --processor argument is not explained.
Not sure if the answer is to use 3 (the 4th option starting from zero) or if 4 is a missing option that needs to be added or if it is something else completely.

My system
``` shell
$ uname -a
Linux frigate 6.6.30-v8+ #1762 SMP PREEMPT Thu May  9 15:17:51 BST 2024 aarch64 GNU/Linux
$ cat /proc/cpuinfo | grep -i model
Model		: Raspberry Pi 5 Model B Rev 1.0
```

**Comment by mikegapinski** [comment]
This issue is related to https://github.com/RPi-Distro/rpi-source/issues/22 and in https://github.com/RPi-Distro/rpi-source/issues/25

This is fixed in a fork https://github.com/jgartrel/rpi-source/

**Comment by mikegapinski** [comment]
@pelwell it is not my fork so I don't feel comfortable with making a pull request with those fixes but they do work. If it looks ok to you it could be merged/cherry-picked

**Comment by djholt** [comment]
@mikegapinski This forked saved me just now—thanks for the pointer!

**Comment by pelwell** [comment]
That fork was also a #29 that was long overdue for merging - now done.

**Comment by askpatrickw** [comment]
I ran this from main and it's working. I guess we can close this issue.
